id: P257BB219
initial_creation_type: input
source_metadata:
  title: Nyingma Mönlam Series
  language: zh
  description: 'The following texts are recited during the annual Nyingma Mönlam prayer
    festival in Bodhgaya:'
  volume:
    9e781d0258e14ffeb518f38d9e9a7a5c:
      title: Verses of the Eight Noble Auspicious Ones
      parent: Eight Auspicious Ones
    6be10ca2d4234dc493998154e88d2606:
      title: The Ritual of the Bodhisattva Vow According to the Tradition of Patrul
        Rinpoche
      parent: Bodhisattva Vow
    e9898c8b3178478c9179906968ac9b38:
      title: The Bodhisattva’s Confession of Downfalls (Nyingma Version)
      parent: Confession
    df2b6c19ed864be9ab7ea44802d76508:
      title: 'Accomplishing the Lama through the Seven-Line Prayer: A Special Teaching
        from the Lama Sangdü'
      parent: Seven-Line Prayer
    fa407e7065bc41de8e6208fc657bd554:
      title: 'The Garland of Utpala Flowers: A Prayer to the Masters of the Lineage
        of Zabtik Drolchok'
      parent: Zabtik Drolchok
    83c4f3994f3b43e58a8650dcaf881553:
      title: 'The Treasury of Blessings: A Practice of Buddha Śākyamuni'
      parent: Śākyamuni Practice
    e3c7893add3a4c5ebde3155811eb7ded:
      title: A Brief Practice for Paying Homage and Making Offerings to the Buddha
        together with his retinue of Arhats
      parent: Sixteen Arhats
    6108d624d0904522a1f9247db4e79073:
      title: The General Visualization for Prayers to Guru Rinpoche
      parent: Guru Rinpoche Visualization
    e169f67606104aea9543c1dde25a1b66:
      title: 'Le''u Dünma—Chapter 1: The Prayer to the Three Kāya Guru'
      parent: Le'u Dünma
    785cf0b252854a5ea8174e38567c5704:
      title: 'Le''u Dünma—Chapter 2: The Prayer Requested by King Tri Songdetsen'
      parent: Le'u Dünma
    887c8a14b6bf4dae8ce63bde81e66856:
      title: 'Le''u Dünma—Chapter 3: The Prayer Requested by Khandro Yeshe Tsogyal'
      parent: Le'u Dünma
    ea0cc158b8a7443086c21b2b2a02e1ca:
      title: 'Le''u Dünma—Chapter 4: The Prayer Requested by Namkhe Nyingpo'
      parent: Le'u Dünma
    f272ad8905564298bc0e8a1afc05587f:
      title: 'Le''u Dünma—Chapter 5: The Prayer Requested by Nanam Dorje Dudjom'
      parent: Le'u Dünma
    0c8d4876420c4ad9a4beb51667c8a699:
      title: 'Le''u Dünma—Chapter 6: The Prayer Requested by Prince Mutri Tsenpo'
      parent: Le'u Dünma
    17859ec726964df9bf71c7cc5a52168e:
      title: Le'u Dünma—Chapter 7. The Prayer to Guru Rinpoche that Spontaneously
        Fulfills All Wishes (Sampa Lhundrupma)
      parent: Le'u Dünma
    456868206e9b496fbdd25b4b4acd387f:
      title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
      parent: Barché Lamsel
    08c4a42a4c9642c2bd1653c36f3b021f:
      title: The Prayer in Six Vajra Lines
      parent: Guru Rinpoche Prayers
    b07e7ba00d91435ab0190dcc80b939be:
      title: The Prayer that Swiftly Fulfils All Wishes (Sampa Nyur Drupma)
      parent: Guru Rinpoche Prayers
    a8c53f8692eb4483b4d8076ed13a8f53:
      title: 'Wisdom''s Bestowal: A Way to Accumulate the Recitation of the Tantra
        ''Chanting the Names of Mañjuśrī'' (Mañjuśrī Nāma Saṃgīti)'
      parent: Chanting the Names of Mañjuśrī
    2119883ae4d04d9ab1f754729dfd182b:
      title: Ārya Mañjuśrī Tantra Garbha
      parent: Mañjuśrī
    b6d16025d4b544bca9f74b318d7092d3:
      title: The Praise to Mañjuśrī—Glorious Wisdom's Excellent Qualities
      parent: Mañjuśrī
    6580ddefcdfd4ae1bd534325e4db2799:
      title: The Heart of the Transcendent Perfection of Wisdom
      parent: Heart Sūtra
    b2301495d80d495abb13e0d9adf0c92a:
      title: The Means for Accomplishment called the Blazing Wheel
      parent: Blazing Wheel
    6fc373ee49694690b8480dde3794d2f7:
      title: 'The Blazing Tower: A Daily Practice of Uṣṇīṣa-Sitātapatrā'
      parent: Sitātapatrā
    129c937d51b84f79b790de9c57950706:
      title: A Daily 'Hand-Clapping' Practice of Siṃhamukhā
      parent: Siṃhamukhā
    4bc0340b87b740639b4a79f78a6e4980:
      title: The Dhāraṇī of Amitāyus
      parent: Dhāraṇī of Amitāyus
    b37f8eedcca042f6b6f47365b6950cd4:
      title: 'The King of Aspiration Prayers: Samantabhadra''s “Aspiration to Good
        Actions” (Zangchö Mönlam)'
      parent: Zangchö Mönlam
    fda3aafa58a1481f80445a88dc355a45:
      title: Maitreya's Aspiration
      parent: Maitreya's Aspiration
    2f7878237bf94d249836f2c304dd463f:
      title: Aspiration to Generate Bodhicitta, Utterly Pure and Supreme
      parent: Aspiration to Generate Bodhicitta
    0b5d6c4a849e421ea5168a505987cfda:
      title: The Powerful Prayer of Aspiration from the Tantra of the Great Perfection
        that Reveals the All-Penetrating Wisdom Mind of Samantabhadra (Kunzang Mönlam)
      parent: Kunzang Mönlam
    fc2a46e235e54b37b11271585c54ade5:
      title: Brief Sukhāvatī Aspiration
      parent: Amitābha Mönlam
    6d772f7722a34ad3833678d9089e0258:
      title: Dedication from Vajravārāhī Cycle of Namchö revealed by Mingyur Dorje
      parent: Amitābha Mönlam
    7cc9a3cfd20a4f30849a2d0c237326b2:
      title: The Aspiration of the Vajradhātu Maṇḍala
      parent: Aspiration of Vajradhātu Maṇḍala
    d53b0676a68942e48ea3e3e019311ca4:
      title: Yeshe Tsogyal's Prayer
      parent: Yeshe Tsogyal’s Prayer
    94d6d2bb4a784273a28a68de8b301613:
      title: Prayer for Dispelling Famine
      parent: Thangtong Gyalpo Prayers
    18fd61dccf2c4937b2888c6fd50d7600:
      title: 'The Verses that Saved Sakya from Sickness: A Prayer for Pacifying the
        Fear of Disease'
      parent: Thangtong Gyalpo Prayers
    5a3b016b3dcd457e9387da2f48441313:
      title: 'The Sage''s Powerful Words of Truth: A Prayer for the Spread of the
        Omniscient Buddha''s Teachings'
      parent: Sage's Powerful Words of Truth
    dd5a15c45ac34292ba2acbb45e4862b7:
      title: 'The Rishi''s Maledictory Incantation: An Invocation of Wisdom Mind and
        Sacred Pledges for Reversing the Disturbances and Agitations of Dark Times
        In the Form of an Aspiration Prayer'
      parent: Rishi's Maledictory Incantation
    3acab4d8de234da7a8af93eb0c340f14:
      title: 'The Adamantine Magical Wheel: Invoking the Profound Pledge of Padmākara,
        the Glorious Victor, to Avert the Final War'
      parent: Adamantine Magical Wheel
    0b3f45adfcca4595bf91f70fdde8047f:
      title: 'The Resounding Drum of Truth: A Prayer and Aspiration'
      parent: Resounding Drum of Truth
    5d78f098b25e466b9500b9dd628d3f5c:
      title: The Prayer of the Words of Truth
      parent: Words of Truth
    af8e159e50dd48d78dd8513173b25e65:
      title: The Prayer of the Ground, Path & Fruition – From the Heart-Essence of
        the Vast Expanse
      parent: Ground, Path & Fruition Prayer
    85c7c2d977d043fe8509fe065ca3d519:
      title: The Secret Vajra Knot
      parent: Secret Vajra Knot
    161e582da28e4bf8b7251cdf0b445daf:
      title: Prayer for the Long Life of His Holiness the Dalai Lama
      parent: Long Life Prayers
    1143981ca4b145b0b991da19dece16a1:
      title: 'The Music of Immortality: A Prayer for the Long Life of His Holiness
        the Dalai Lama'
      parent: Long Life Prayers
    8a080c8dc6d340969cf4a0b93d49712d:
      title: General Long-Life Prayer
      parent: Long Life Prayers
    3ddca04daafa4d319c30bf1ce2a0490c:
      title: 'The Melodious Song of Immortality: A Prayer for Long Life'
      parent: Long Life Prayers
    07ba45ed662144a7b499f2370bce8514:
      title: 'Words to Delight the Sovereigns of the Dharma: A Prayer of Aspiration
        for the Flourishing and Spread of the Ancient Translation Tradition'
      parent: Prayer for Spread of Nyingma Tradition
    e15fe915e0734c1a9ad2c19561b4df22:
      title: 'Final Words: The Essential Advice'
      parent: Final Words
created_at: '2022-03-01T04:58:17.002144'
last_modified_at: '2022-03-01T04:58:17.002147'
